In [26]:
import numpy as np

In [27]:
import pandas as pd

In [28]:
import matplotlib.pyplot as plt

In [29]:
from sklearn.preprocessing import StandardScaler

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
from sklearn import svm

In [32]:
from sklearn.metrics import accuracy_score

In [33]:
# data collection and analysis

In [34]:
diabetes_dataset = pd.read_csv("diabetes.csv")

In [35]:
diabetes_dataset.head(5)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [36]:
# number of rows and colums

In [37]:
diabetes_dataset.shape

(768, 9)

In [38]:
diabetes_dataset.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [39]:
diabetes_dataset["Outcome"].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [40]:
# seperating the data and labels 
X = diabetes_dataset.drop(columns = "Outcome", axis = 1)
Y = diabetes_dataset["Outcome"]

In [41]:
print(X)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age
0                       0.627   50
1                       0.351   31
2                       0.672   32
3                       0.167   21
4                       2.288   33
..                        ...  ...
763                     0.171   63
764                     0.340   27
765                     0.245   30
766                     0.349   47
767                     0.315   23

[768 rows x 8 columns]

In [42]:
diabetes_dataset.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [43]:
# Data standardization

In [44]:
scaler = StandardScaler()

In [45]:
scaler.fit(X)

StandardScaler()

In [46]:
Standardized_data = scaler.transform(X)

In [47]:

print(Standardized_data)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]

In [49]:
# train test split, 
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, stratify=Y, random_state=2)

In [50]:
print(X.shape, X_train.shape, X_test.shape)

(768, 8) (614, 8) (154, 8)

In [51]:
# training the model

In [53]:
classifier = svm.SVC(kernel='linear')

In [54]:
# training the support vector machine classifier

In [55]:
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

In [63]:
# model evaluation

In [64]:
# accuracy score

In [65]:
X_train_prediction = classifier.predict(X_train)

In [67]:
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [68]:
print('accuracy score of the training data:', training_data_accuracy)

accuracy score of the training data: 0.7833876221498371

In [69]:
# accuracy score on test data

In [70]:
X_test_prediction = classifier.predict(X_test)
testing_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [72]:
print('accuracy score of the tasting data:', testing_data_accuracy)

accuracy score of the tasting data: 0.7727272727272727

In [73]:
# making prediction

In [84]:
input_data = (4, 110, 92, 0, 0, 37.6, 0.191, 30)

In [85]:
# changing the the input_data to numpy array

In [86]:
input_data_as_numpy_array = np.asarray(input_data)

In [87]:
# we need to reshape this data

In [88]:
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

In [93]:
std_data = scaler.transform(input_data_reshaped)
print(std_data)

[[ 0.04601433 -0.34096773  1.18359575 -1.28821221 -0.69289057  0.71168975
  -0.84827977 -0.27575966]]

C:\Users\ORSU SANTOSH\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [94]:
prediction = classifier.predict(input_data_reshaped)

C:\Users\ORSU SANTOSH\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [95]:
if (prediction[0] == 0):
    print("the person is not diabetic")
else:
    print("the person is diabetic")

the person is not diabetic